### ISSUE TITLE
o365: login blocked: "The resource principal was not found in the tenant"

### ISSUE THREAD

**Issue by ghost** [muraenateam/muraena#81]

**Comment by kwekudumebi** [comment]
can you share your configuration details

**Comment by Markb1337** [comment]
I think I ran into the same issue as ghost. See attached screenshot. This occurs after providing username and password, on a managed domain. 

Don't see anything unusual in the Muraena log. Don't have a lot of time right now so can't go through the raw requests in detail at the moment.

What I can say though: This bug(?) happens when using the Muraena binary with version: "Muraena v1.7 (built for linux amd64 with go1.15.15)". The issue is resolved when using an older(!) Muraena binary which I had laying around: "Muraena v1.4.1b (built for linux amd64 with go1.17)". Something in the newer version breaks the flow..

![bug](https://user-images.githubusercontent.com/15806113/179229450-fec3f803-3283-460d-9e3a-70492f81cb9b.png)
